### ISSUE TITLE
Option do disable/ enable the crosshair on overlays

### ISSUE THREAD

**Issue by Turioyt** [kel-cu/CamOverlay#2]
Good day. Thank you for making this mod. It has become a must have for me for immersion.
However, there is one issue I have and that is how some overlays have a crosshair (namelyCamikonShot and KlashRaick) in the middle of the screen. I understand that it might've been done on purpose because of the type of camera it's trying to emulate but it can be a bit distracting in certain screenshots. So I propose a setting that can enable and disable said crosshair. It would also allow for a bit more user customization which I think is always a plus for a mod like this.
Anyways, thanks again for this mod. Hope you have a good day.

**Comment by kel-cu** [comment]
Good day, thank you for your kind words :3
About the crosshair, I was thinking of making configs for overlays that would allow you to disable certain elements

**Comment by kel-cu** [comment]
Added in 2.0.0-alpha.1
