### ISSUE TITLE
How to change cinematic overlay time to game time instead of device time.

### ISSUE THREAD

**Issue by Turioyt** [kel-cu/CamOverlay#3]
Currently, the cinematic overlay shows time but it is the device's time and not game time. I'm aware that I can change that in the overlays category but I don't know how. What would I change the bottom text into to do so. 
Thanks in advance. and thank you again for making this mod.

**Comment by kel-cu** [comment]
{time}?

**Comment by kel-cu** [comment]
{world.time_formatted}*

**Comment by Turioyt** [comment]
Thank you! That works 😊
